/**
 * BookMonkey 4 API
 * **DEMO**  This is a demo backend for serving books. All data is erased after some inactivity.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * An Object which contains neccessary keys (PushEncryptionKeyName), see https://www.w3.org/TR/push-api/#dom-pushsubscriptionjson-keys
 */
export interface Keys { 
    /**
     * The auth value is used to retrieve the authentication secret described in RFC8291 (https://tools.ietf.org/html/rfc8291)
     */
    auth: string;
    /**
     * The p256dh value is used to retrieve the P-256 ECDH Diffie-Hellman public key described in RFC8291 (https://tools.ietf.org/html/rfc8291)
     */
    p256dh: string;
}
